version: '2'
services:
    finologee-app:
        image: finologee
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://finologee-postgresql:5432/finologee
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    finologee-postgresql:
        extends:
            file: postgresql.yml
            service: finologee-postgresql
